apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    component: kafk
  name: helk-kafka-broker
spec:
  ports:
  - name: transport
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    component: kafka
  type: LoadBalancer
