apiVersion: v1
kind: Service
metadata:
  labels:
    component: logstash
  name: helk-logstash
spec:
  ports:
  - port: 4560
    protocol: TCP
    targetPort: 4560
  selector:
    component: logstash
  type: ClusterIP
