apiVersion: v1
kind: Service
metadata:
  labels:
    component: zookeeper
  name: helk-zookeeper
spec:
  ports:
  - name: zookeeper
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    component: zookeeper
  type: ClusterIP
