apiVersion: v1
kind: Service
metadata:
  labels:
    component: elasticsearch
  name: helk-elasticsearch
spec:
  ports:
  - name: transport
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elasticsearch
  type: ClusterIP
