apiVersion: v1
data:
  kafka-create-topics.sh: "#!/bin/bash\n\n# HELK script: kafka-create-topics.sh\n#
    HELK script description: creates kafka topics\n# HELK build Stage: Alpha\n# Author:
    Roberto Rodriguez (@Cyb3rWard0g)\n# License: GPL-3.0\n\n# *********** Waiting
    for Kafka broker to be up ***************\necho \"[HELK-DOCKER-INSTALLATION-INFO]
    Checking to see if Kafka broker is up...\"\nwhile [[ \"$(curl -sm5 $KAFKA_BROKER_NAME:$KAFKA_BROKER_PORT
    -o /dev/null; echo $?)\" != 56 ]] ; do\n  echo \"[HELK-DOCKER-INSTALLATION-INFO]
    Kafka broker $KAFKA_BROKER_NAME is not available yet\"\n  sleep 1\ndone\n\n# ***********
    Creating Kafka Topics**************\n#Reference:https://stackoverflow.com/questions/10586153/split-string-into-an-array-in-bash\nIFS=',
    ' read -r -a temas <<< \"$KAFKA_CREATE_TOPICS\"\n\nfor t in ${temas[@]}; do \n
    \ echo \"[HELK-DOCKER-INSTALLATION-INFO] Creating Kafka ${t} Topic..\"\n  ${KAFKA_HOME}/bin/kafka-topics.sh
    --create --zookeeper ${ZOOKEEPER_NAME}:2181 --replication-factor ${REPLICATION_FACTOR}
    --partitions 1 --topic ${t} --if-not-exists\ndone\n\nwait\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"kafka-create-topics.sh":"#!/bin/bash\n\n# HELK script: kafka-create-topics.sh\n# HELK script description: creates kafka topics\n# HELK build Stage: Alpha\n# Author: Roberto Rodriguez (@Cyb3rWard0g)\n# License: GPL-3.0\n\n# *********** Waiting for Kafka broker to be up ***************\necho \"[HELK-DOCKER-INSTALLATION-INFO] Checking to see if Kafka broker is up...\"\nwhile [[ \"$(curl -sm5 $KAFKA_BROKER_NAME:$KAFKA_BROKER_PORT -o /dev/null; echo $?)\" != 56 ]] ; do\n  echo \"[HELK-DOCKER-INSTALLATION-INFO] Kafka broker $KAFKA_BROKER_NAME is not available yet\"\n  sleep 1\ndone\n\n# *********** Creating Kafka Topics**************\n#Reference:https://stackoverflow.com/questions/10586153/split-string-into-an-array-in-bash\nIFS=', ' read -r -a temas \u003c\u003c\u003c \"$KAFKA_CREATE_TOPICS\"\n\nfor t in ${temas[@]}; do \n  echo \"[HELK-DOCKER-INSTALLATION-INFO] Creating Kafka ${t} Topic..\"\n  ${KAFKA_HOME}/bin/kafka-topics.sh --create --zookeeper ${ZOOKEEPER_NAME}:2181 --replication-factor ${REPLICATION_FACTOR} --partitions 1 --topic ${t} --if-not-exists\ndone\n\nwait\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"kafka-create-topics","namespace":"helk"}}
  creationTimestamp: null
  name: kafka-create-topics
