apiVersion: v1
kind: Service
metadata:
  labels:
    component: elasticsearch
  name: helk-elasticsearch
spec:
  ports:
  - name: transport
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elasticsearch
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: elasticsearch
  name: helk-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - command:
        - bash
        - /usr/share/elasticsearch/scritps/elasticsearch-entrypoint.sh
        env:
        - name: CLUSTER_NAME
          value: helk-cluster
        - name: NODE_NAME
          value: helk-1
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: ES_JAVA_OPTS
          value: -Xms2g -Xmx2g
        - name: NETWORK_HOST
          value: _eth0_
        - name: PROCESSORS
          value: "1"
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        imagePullPolicy: IfNotPresent
        name: helk-elasticsearch
        ports:
        - containerPort: 9200
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: elasticsearch-yml
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/scritps/elasticsearch-entrypoint.sh
          name: elasticsearch-entrypoint
          subPath: elasticsearch-entrypoint.sh
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        resources: {}
        securityContext:
          privileged: true
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: elasticsearch-yml
        name: elasticsearch-yml
      - configMap:
          defaultMode: 420
          name: elasticsearch-entrypoint
        name: elasticsearch-entrypoint
