apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"elastalert"},"name":"helk-elastalert","namespace":"helk"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"component":"elastalert"}},"spec":{"containers":[{"env":[{"name":"ES_HOST","value":"helk-elastalert"},{"name":"ES_PORT","value":"9200"}],"image":"cyb3rward0g/helk-elastalert:0.2.1","name":"helk-elastalert"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    component: elastalert
  name: helk-elastalert
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: elastalert
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: elastalert
    spec:
      containers:
      - env:
        - name: ES_HOST
          value: helk-elastalert
        - name: ES_PORT
          value: "9200"
        image: cyb3rward0g/helk-elastalert:0.2.1
        imagePullPolicy: IfNotPresent
        name: helk-elastalert
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
