apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"helk-ksql-server"},"name":"helk-ksql-server","namespace":"helk"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"component":"helk-ksql-server"}},"spec":{"containers":[{"env":[{"name":"KSQL_BOOTSTRAP_SERVERS","value":"helk-kafka-broker:9092"},{"name":"KSQL_LISTENERS","value":"http://0.0.0.0:8088"},{"name":"KSQL_KSQL_SERVICE_ID","value":"wardog"},{"name":"KSQL_CUB_KAFKA_TIMEOUT","value":"300"},{"name":"KSQL_KSQL_COMMIT_INTERVAL_MS","value":"2000"},{"name":"KSQL_KSQL_CACHE_MAX_BYTES_BUFFERING","value":"10000000"},{"name":"KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET","value":"earliest"},{"name":"KSQL_HEAP_OPTS","value":"-Xmx1g"}],"image":"confluentinc/cp-ksql-server:5.1.2","name":"helk-ksql-server","ports":[{"containerPort":8088}]}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    component: helk-ksql-server
  name: helk-ksql-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: helk-ksql-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: helk-ksql-server
    spec:
      containers:
      - env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: helk-kafka-broker:9092
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_KSQL_SERVICE_ID
          value: wardog
        - name: KSQL_CUB_KAFKA_TIMEOUT
          value: "300"
        - name: KSQL_KSQL_COMMIT_INTERVAL_MS
          value: "2000"
        - name: KSQL_KSQL_CACHE_MAX_BYTES_BUFFERING
          value: "10000000"
        - name: KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET
          value: earliest
        - name: KSQL_HEAP_OPTS
          value: -Xmx1g
        image: confluentinc/cp-ksql-server:5.1.2
        imagePullPolicy: IfNotPresent
        name: helk-ksql-server
        ports:
        - containerPort: 8088
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
