apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.alpha.kubernetes.io/tolerate-unready-endpoints":"true"},"labels":{"component":"helk-zookeeper"},"name":"helk-zookeeper","namespace":"helk"},"spec":{"ports":[{"name":"zookeeper","port":2181,"protocol":"TCP"}],"selector":{"component":"helk-zookeeper"}}}
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: null
  labels:
    component: helk-zookeeper
  name: helk-zookeeper
spec:
  ports:
  - name: zookeeper
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    component: helk-zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
