apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"component":"helk-ksql-server"},"name":"helk-ksql-server","namespace":"helk"},"spec":{"ports":[{"port":8088}],"selector":{"component":"helk-ksql-server"}}}
  creationTimestamp: null
  labels:
    component: helk-ksql-server
  name: helk-ksql-server
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    component: helk-ksql-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
