apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.0.12.135"],"port":32383,"protocol":"TCP","serviceName":"helk:helk-kibana","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.alpha.kubernetes.io/tolerate-unready-endpoints":"true"},"labels":{"role":"kibana"},"name":"helk-kibana","namespace":"helk"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":5601}],"selector":{"role":"kibana"},"type":"NodePort"}}
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: null
  labels:
    role: kibana
  name: helk-kibana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    role: kibana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
