apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"component":"elasticsearch"},"name":"helk-elasticsearch","namespace":"helk"},"spec":{"ports":[{"name":"transport","port":9200,"protocol":"TCP"}],"selector":{"component":"elasticsearch"}}}
  creationTimestamp: null
  labels:
    component: elasticsearch
  name: helk-elasticsearch
spec:
  ports:
  - name: transport
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elasticsearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
