apiVersion: v1
kind: Service
metadata:
  labels:
    component: kibana
  name: helk-kibana
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    component: kibana
  type: ClusterIP
