apiVersion: v1
kind: Service
metadata:
  labels:
    component: ksql-server
  name: helk-ksql-server
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    component: ksql-server
  type: ClusterIP
