apiVersion: v1
kind: Service
metadata:
  labels:
    component: helk-zookeeper
  name: helk-zookeeper
spec:
  ports:
  - name: zookeeper
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    component: helk-zookeeper
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: helk-zookeeper
  name: helk-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: helk-zookeeper
  template:
    metadata:
      labels:
        component: helk-zookeeper
    spec:
      containers:
      - image: cyb3rward0g/helk-zookeeper:2.1.0
        name: helk-zookeeper
