apiVersion: v1
kind: Service
metadata:
  labels:
    role: helk-kibana
  name: helk-kibana
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    role: helk-kibana
  type: ClusterIP

---
apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    role: helk-kibana
  name: helk-kibana
spec:
  replicas: 1
  selector:
    role: helk-kibana
  template:
    metadata:
      labels:
        role: helk-kibana
    spec:
      containers:
      - command:
        - bash
        - /usr/share/kibana/scripts/kibana-entrypoint.sh
        env:
        - name: KIBANA_ES_URL
          value: http://helk-elasticsearch:9200
        - name: CLUSTER_NAME
          value: helk-cluster
        - name: SERVER_HOST
          value: localhost
        - name: SERVER_PORT
          value: "5601"
        image: docker.elastic.co/kibana/kibana:6.6.1
        name: helk-kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/kibana/config
          name: kibana-yml
        - mountPath: /usr/share/kibana/dashboards
          name: kibana-dashboards
        - mountPath: /usr/share/kibana/scripts
          name: kibana-entrypoint
        - mountPath: /usr/share/kibana/logs
          name: logs
      volumes:
      - configMap:
          defaultMode: 420
          name: kibana-yml
        name: kibana-yml
      - configMap:
          defaultMode: 511
          name: kibana-entrypoint
        name: kibana-entrypoint
      - configMap:
          defaultMode: 420
          name: kibana-dashboards
        name: kibana-dashboards
      - emptyDir: {}
        name: logs
