apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    component: helk-kafka-broker
  name: helk-kafka-broker
spec:
  ports:
  - name: transport
    port: 9092
    nodePort: 31111
    protocol: TCP
    targetPort: 9092
  selector:
    component: helk-kafka-broker
  type: LoadBalancer
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: helk-kafka-broker
  name: helk-kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      component: helk-kafka-broker
  serviceName: helk-kafka-broker
  template:
    metadata:
      labels:
        component: helk-kafka-broker
    spec:
      hostAliases:
      - ip: "kafka-hack-ip"
        hostnames:
        - "kafka-hack"
      containers:
      - env:
        - name: KAFKA_BROKER_NAME
          value: helk-kafka-broker
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_BROKER_PORT
          value: "9092"
        - name: REPLICATION_FACTOR
          value: "1"
        - name: ADVERTISED_LISTENER
          value: ADVERTISED_LISTENER_IP
        - name: ADVERTISED_LISTENER_PORT
          value: "31111"
        - name: KAFKA_CREATE_TOPICS
          value: winlogbeat, SYSMON_JOIN, filebeat, winsysmon, winsecurity
        - name: KAFKA_HEAP_OPTS
          value: -Xmx1G -Xms1G
        - name: LOG_RETENTION_HOURS
          value: "4"
        - name: ZOOKEEPER_NAME
          value: helk-zookeeper
        image: cyb3rward0g/helk-kafka-broker:2.1.0
        name: helk-kafka-broker
        ports:
        - containerPort: 9092
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/helk/kafka/scripts/kafka-entrypoint.sh
          name: kafka-entrypoint
          subPath: kafka-entrypoint.sh
      volumes:
      - configMap:
          defaultMode: 0777
          name: kafka-entrypoint
        name: kafka-entrypoint
      - configMap:
          defaultMode: 511
          name: kafka-create-topics
        name: kafka-create-topics
